aaa1

diff --git a/.github/workflows/a.yml b/.github/workflows/a.yml
--- a/.github/workflows/a.yml
+++ b/.github/workflows/a.yml
@@ -1,23 +1,19 @@
-name: Website Deployment
-on:
-  push:
-    branches:
-      - master
-
 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
+
       - run: npm ci
 
       - name: Run tests
         id: run-tests
-        run: npm run test || exit 1  # will fail if tests fail
+        run: |
+          npm run test || echo "Tests failed" && exit 1
 
       - name: Upload test report on failure
-        if: steps.run-tests.outcome == 'failure'   # ✅ runs only if tests fail
-        uses: actions/upload-artifact@v3
+        if: failure() && steps.run-tests.outcome == 'failure'
+        uses: actions/upload-artifact@v4
         with:
           name: test-report
           path: test.json
